/**
 * Beschriftungen des Aktivitäten-Logs (Seite „Verlauf“, Dashboard-Karte).
 * Die Sichtbarkeit der Einträge regelt der Server (`api/lib/auditVisibility.ts`).
 */

// Deutsche Beschreibungen der Audit-Log-Aktionen (Fallback: roher action-Key)
export const AUDIT_ACTION_LABELS: Record<string, string> = {
  "account.created": "Konto angelegt",
  "account.updated": "Konto bearbeitet",
  "account.deleted": "Konto gelöscht",
  "account.privacy": "Konto-Sichtbarkeit geändert",
  "account.permission": "Konto-Freigabe geändert",
  "account.reconciled": "Kontoabgleich gebucht",
  "category.created": "Kategorie angelegt",
  "category.updated": "Kategorie bearbeitet",
  "category.deleted": "Kategorie gelöscht",
  "transaction.created": "Buchung erfasst",
  "transaction.updated": "Buchung bearbeitet",
  "transaction.deleted": "Buchung gelöscht",
  "transaction.imported": "Buchungen importiert",
  "transaction.tags": "Tags einer Buchung geändert",
  "tag.created": "Tag angelegt",
  "tag.deleted": "Tag gelöscht",
  "budget.saved": "Budget gespeichert",
  "budget.deleted": "Budget gelöscht",
  "recurring.created": "Dauerbuchung angelegt",
  "recurring.updated": "Dauerbuchung bearbeitet",
  "recurring.toggled": "Dauerbuchung umgeschaltet",
  "recurring.deleted": "Dauerbuchung gelöscht",
  "goal.created": "Sparziel angelegt",
  "goal.updated": "Sparziel-Stand geändert",
  "goal.deleted": "Sparziel gelöscht",
  "goal.archived": "Sparziel abgeschlossen und archiviert",
  "goal.restored": "Sparziel aus dem Archiv geholt",
  "goal.contribution.added": "Sparziel-Beitrag hinzugefügt",
  "goal.contribution.deleted": "Sparziel-Beitrag gelöscht",
  "goal.sourceAdded": "Sparziel mit Konto verknüpft",
  "goal.sourceDeleted": "Sparziel-Verknüpfung gelöst",
  "project.created": "Projekt angelegt",
  "project.deleted": "Projekt gelöscht",
  "splitTemplate.created": "Aufteilungsvorlage angelegt",
  "splitTemplate.deleted": "Aufteilungsvorlage gelöscht",
  "mortgage.property.created": "Liegenschaft angelegt",
  "mortgage.property.updated": "Liegenschaft bearbeitet",
  "mortgage.property.deleted": "Liegenschaft gelöscht",
  "mortgage.tranche.created": "Hypothekar-Tranche angelegt",
  "mortgage.tranche.updated": "Hypothekar-Tranche bearbeitet",
  "mortgage.tranche.deleted": "Hypothekar-Tranche gelöscht",
  "mortgage.amortization.created": "Amortisation angelegt",
  "mortgage.amortization.updated": "Amortisation bearbeitet",
  "mortgage.amortization.deleted": "Amortisation gelöscht",
  "mortgage.interest.transferred": "Hypothekarzins als Dauerbuchung übernommen",
  "mortgage.amortization.transferred": "Amortisation als Dauerbuchung übernommen",
  "insurance.policy.created": "Police angelegt",
  "insurance.policy.updated": "Police bearbeitet",
  "insurance.policy.deleted": "Police gelöscht",
  "insurance.coverage.created": "Deckung hinzugefügt",
  "insurance.coverage.updated": "Deckung bearbeitet",
  "insurance.coverage.deleted": "Deckung gelöscht",
  "insurance.premium.transferred": "Prämie als Dauerbuchung übernommen",
  "insurance.gap.dismissed": "Deckungs-Hinweis ausgeblendet",
  "insurance.gap.restored": "Deckungs-Hinweis eingeblendet",
  // Vorsorge: privat pro Benutzer — der Server liefert nur die eigenen Einträge
  "pension.profile.updated": "Vorsorgeprofil geändert",
  "pension.salary.created": "Lohn erfasst",
  "pension.salary.updated": "Lohn bearbeitet",
  "pension.salary.deleted": "Lohn gelöscht",
  "pension.salary.transferred": "Nettolohn als Dauerbuchung übernommen",
  "pension.deduction.created": "Lohnabzug angelegt",
  "pension.deduction.updated": "Lohnabzug bearbeitet",
  "pension.deduction.deleted": "Lohnabzug gelöscht",
  "pension.ahv.updated": "AHV-Daten geändert",
  "pension.fund.created": "Vorsorgekonto angelegt",
  "pension.fund.updated": "Vorsorgekonto bearbeitet",
  "pension.fund.deleted": "Vorsorgekonto gelöscht",
  "pension.pillar3.created": "Säule-3a-Konto angelegt",
  "pension.pillar3.updated": "Säule-3a-Konto bearbeitet",
  "pension.pillar3.deleted": "Säule-3a-Konto gelöscht",
  "data.imported": "Daten importiert",
  "data.reset": "Finanzdaten zurückgesetzt",
  "settings.currency": "Währung geändert",
  "settings.notify": "Benachrichtigungen geändert",
  "auth.login": "Angemeldet",
  "auth.login.failed": "Anmeldung fehlgeschlagen",
  "auth.logout": "Abgemeldet",
  "user.created": "Benutzer angelegt",
  "user.deactivated": "Benutzer deaktiviert",
  "user.reactivated": "Benutzer reaktiviert",
  "user.updated": "Profil geändert",
  "user.passwordChanged": "Passwort geändert",
  "user.totp.enabled": "2FA aktiviert",
  "user.totp.disabled": "2FA deaktiviert",
};

// Entity-Gruppen für den Filter in der Aktivitäten-Card
export const AUDIT_ENTITY_GROUPS: [string, string, string[]][] = [
  ["account", "Konten", ["account"]],
  ["transaction", "Buchungen", ["transaction"]],
  ["category", "Kategorien", ["category"]],
  ["tag", "Tags", ["tag"]],
  ["budget", "Budgets", ["budget"]],
  ["recurring", "Dauerbuchungen", ["recurring"]],
  ["goal", "Sparziele", ["goal"]],
  ["mortgage", "Hypotheken", ["mortgage"]],
  ["insurance", "Versicherungen", ["insurance"]],
  ["pension", "Vorsorge", ["pension"]],
  ["project", "Projekte", ["project", "splitTemplate"]],
  ["user", "Benutzer", ["user", "auth"]],
  ["settings", "Einstellungen", ["settings", "data"]],
];
